<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FasilitasKesehatan;
use App\Models\JenisFasilitas;

class FasilitasKesehatanSeeder extends Seeder
{
    public function run(): void
    {
        // Ambil ID jenis faskes dari database (harus sudah di-seed duluan)
        $rs  = JenisFasilitas::where('nama_jenis', 'Rumah Sakit')->value('id');
        $pkm = JenisFasilitas::where('nama_jenis', 'Puskesmas')->value('id');
        $kln = JenisFasilitas::where('nama_jenis', 'Klinik')->value('id');
        $apt = JenisFasilitas::where('nama_jenis', 'Apotek')->value('id');
        $opt = JenisFasilitas::where('nama_jenis', 'Optik')->value('id');

        $data = [

            // ══════════════════════════════════════
            // RUMAH SAKIT (4 data)
            // ══════════════════════════════════════
            [
                'kode_faskes'            => '0210R001',
                'nama_faskes'            => 'RSUD Dr. Ferdinand Lumbantobing',
                'jenis_faskes_id'        => $rs,
                'kategori'               => 'RS Umum Pemerintah Daerah (Kelas B)',
                'alamat'                 => 'Jl. Dr. F.L. Tobing No.35',
                'kelurahan'              => 'Kota Beringin',
                'kecamatan'              => 'Sibolga Kota',
                'kode_pos'               => '22521',
                'telepon'                => '0631-21444',
                'jam_operasional'        => '24 Jam',
                'kapasitas_tempat_tidur' => 200,
                'akreditasi'             => 'Paripurna',
                'status_kepemilikan'     => 'Pemerintah Daerah',
                'kelas_rs'               => 'Kelas B',
                'bpjs'                   => true,
                'latitude'               => 1.7432,
                'longitude'              => 98.7778,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.743200000000000,98.777799999999999',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '0034R004',
                'nama_faskes'            => 'RS Metta Medika Sibolga',
                'jenis_faskes_id'        => $rs,
                'kategori'               => 'RS Umum Swasta (Kelas C)',
                'alamat'                 => 'Jl. Sutoyo Siswomiharjo No.34',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Kota',
                'kode_pos'               => '22522',
                'telepon'                => '0631-25007',
                'jam_operasional'        => '24 Jam',
                'kapasitas_tempat_tidur' => 79,
                'akreditasi'             => 'Madya',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => 'Kelas C',
                'bpjs'                   => true,
                'latitude'               => 1.7414,
                'longitude'              => 98.7813,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.741400000000000,98.781300000000002',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '0035R005',
                'nama_faskes'            => 'RS Metta Medika 2 Sibolga',
                'jenis_faskes_id'        => $rs,
                'kategori'               => 'RS Umum Swasta (Kelas C)',
                'alamat'                 => 'Jl. Diponegoro No.6-8',
                'kelurahan'              => 'Pancuran Gerobak',
                'kecamatan'              => 'Sibolga Kota',
                'kode_pos'               => '22522',
                'telepon'                => '81269412440',
                'jam_operasional'        => '24 Jam',
                'kapasitas_tempat_tidur' => 100,
                'akreditasi'             => 'Madya',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => 'Kelas C',
                'bpjs'                   => true,
                'latitude'               => 1.7406,
                'longitude'              => 98.7817,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.740600000000000,98.781700000000001',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '340001',
                'nama_faskes'            => 'RS Rumkitban 01.08.02 Sibolga',
                'jenis_faskes_id'        => $rs,
                'kategori'               => 'RS Umum TNI/Polri (Kelas D Pratama)',
                'alamat'                 => 'Jl. Sisingamangaraja No.1',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Selatan',
                'kode_pos'               => '22521',
                'telepon'                => '0631-21199',
                'jam_operasional'        => '24 Jam',
                'kapasitas_tempat_tidur' => 50,
                'akreditasi'             => 'Dasar',
                'status_kepemilikan'     => 'TNI/Polri',
                'kelas_rs'               => 'Kelas D Pratama',
                'bpjs'                   => true,
                'latitude'               => 1.7277,
                'longitude'              => 98.7996,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.727700000000000,98.799599999999998',
                'status'                 => 'Aktif',
            ],

            // ══════════════════════════════════════
            // PUSKESMAS (9 data)
            // ══════════════════════════════════════
            [
                'kode_faskes'            => '2100101',
                'nama_faskes'            => 'Puskesmas Sambas',
                'jenis_faskes_id'        => $pkm,
                'kategori'               => 'Puskesmas',
                'alamat'                 => 'Jl. Tongkol No.11',
                'kelurahan'              => 'Sambas',
                'kecamatan'              => 'Sibolga Kota',
                'kode_pos'               => '22524',
                'telepon'                => '0631-22891',
                'jam_operasional'        => '07:30-21:00',
                'kapasitas_tempat_tidur' => 10,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Pemerintah Daerah',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7375,
                'longitude'              => 98.7831,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.737500000000000,98.783100000000005',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '2100201',
                'nama_faskes'            => 'Puskesmas Aek Habil',
                'jenis_faskes_id'        => $pkm,
                'kategori'               => 'Puskesmas',
                'alamat'                 => 'Jl. Merpati No.58',
                'kelurahan'              => 'Aek Habil',
                'kecamatan'              => 'Sibolga Selatan',
                'kode_pos'               => '22521',
                'telepon'                => '0631-21520',
                'jam_operasional'        => '07:30-21:00',
                'kapasitas_tempat_tidur' => 10,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Pemerintah Daerah',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7282,
                'longitude'              => 98.7946,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.728200000000000,98.794600000000003',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '2100301',
                'nama_faskes'            => 'Puskesmas Pintu Angin',
                'jenis_faskes_id'        => $pkm,
                'kategori'               => 'Puskesmas',
                'alamat'                 => 'Jl. Oswald Siahaan No.53',
                'kelurahan'              => 'Pancuran Dewa',
                'kecamatan'              => 'Sibolga Utara',
                'kode_pos'               => '22521',
                'telepon'                => '0631-21438',
                'jam_operasional'        => '07:30-21:00',
                'kapasitas_tempat_tidur' => 10,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Pemerintah Daerah',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7493,
                'longitude'              => 98.7716,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.749300000000000,98.771600000000007',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '2100401',
                'nama_faskes'            => 'Puskesmas Pelabuhan Sambas',
                'jenis_faskes_id'        => $pkm,
                'kategori'               => 'Puskesmas',
                'alamat'                 => 'Jl. Horas Ujung No.171',
                'kelurahan'              => 'Sibolga Ilir',
                'kecamatan'              => 'Sibolga Sambas',
                'kode_pos'               => '22521',
                'telepon'                => '0631-21650',
                'jam_operasional'        => '07:30-21:00',
                'kapasitas_tempat_tidur' => 10,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Pemerintah Daerah',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7308,
                'longitude'              => 98.7825,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.730800000000000,98.782499999999999',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '340402',
                'nama_faskes'            => 'Puskesmas Aek Parombunan',
                'jenis_faskes_id'        => $pkm,
                'kategori'               => 'Puskesmas',
                'alamat'                 => 'Jl. Sudirman Aek Parombunan',
                'kelurahan'              => 'Aek Parombunan',
                'kecamatan'              => 'Sibolga Selatan',
                'kode_pos'               => '22524',
                'telepon'                => '0631-22345',
                'jam_operasional'        => '07:30-21:00',
                'kapasitas_tempat_tidur' => 10,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Pemerintah Daerah',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7302,
                'longitude'              => 98.8014,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.730200000000000,98.801400000000001',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => 'PKM-PUSTU-001',
                'nama_faskes'            => 'Puskesmas Pembantu Sibolga Ilir',
                'jenis_faskes_id'        => $pkm,
                'kategori'               => 'Puskesmas Pembantu',
                'alamat'                 => 'Jl. Barangin No.5',
                'kelurahan'              => 'Sibolga Ilir',
                'kecamatan'              => 'Sibolga Utara',
                'kode_pos'               => '22521',
                'telepon'                => '-',
                'jam_operasional'        => '07:30-14:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Pemerintah Daerah',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7497,
                'longitude'              => 98.7693,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.749700000000000,98.769300000000001',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => 'PKM-PUSTU-003',
                'nama_faskes'            => 'Puskesmas Pembantu Pancuran Pinang',
                'jenis_faskes_id'        => $pkm,
                'kategori'               => 'Puskesmas Pembantu',
                'alamat'                 => 'Jl. Pancuran Pinang No.3',
                'kelurahan'              => 'Pancuran Pinang',
                'kecamatan'              => 'Sibolga Selatan',
                'kode_pos'               => '22521',
                'telepon'                => '-',
                'jam_operasional'        => '07:30-14:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Pemerintah Daerah',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7250,
                'longitude'              => 98.7996,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.725000000000000,98.799599999999998',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => 'PKM-PUSTU-004',
                'nama_faskes'            => 'Puskesmas Pembantu Aek Manis',
                'jenis_faskes_id'        => $pkm,
                'kategori'               => 'Puskesmas Pembantu',
                'alamat'                 => 'Jl. Aek Manis No.3',
                'kelurahan'              => 'Aek Manis',
                'kecamatan'              => 'Sibolga Selatan',
                'kode_pos'               => '22523',
                'telepon'                => '-',
                'jam_operasional'        => '07:30-14:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Pemerintah Daerah',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7289,
                'longitude'              => 98.7947,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.728900000000000,98.794700000000006',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => 'PKM-PUSTU-005',
                'nama_faskes'            => 'Puskesmas Pembantu Simare-mare',
                'jenis_faskes_id'        => $pkm,
                'kategori'               => 'Puskesmas Pembantu',
                'alamat'                 => 'Jl. Simare-mare No.7',
                'kelurahan'              => 'Simare-mare',
                'kecamatan'              => 'Sibolga Utara',
                'kode_pos'               => '22523',
                'telepon'                => '-',
                'jam_operasional'        => '07:30-14:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Pemerintah Daerah',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7459,
                'longitude'              => 98.7714,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.745900000000000,98.771400000000000',
                'status'                 => 'Aktif',
            ],

            // ══════════════════════════════════════
            // KLINIK (9 data)
            // ══════════════════════════════════════
            [
                'kode_faskes'            => '0034B003',
                'nama_faskes'            => 'Klinik Harapan Bunda',
                'jenis_faskes_id'        => $kln,
                'kategori'               => 'Klinik Pratama',
                'alamat'                 => 'Jl. Elang No.35',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Sambas',
                'kode_pos'               => '22521',
                'telepon'                => '0631-22456',
                'jam_operasional'        => '08:00-20:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7342,
                'longitude'              => 98.7904,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.734200000000000,98.790400000000005',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '0034U001',
                'nama_faskes'            => 'Praktek Dokter Dr. Tony Giovanno Sinaga',
                'jenis_faskes_id'        => $kln,
                'kategori'               => 'Dokter Praktik Perorangan',
                'alamat'                 => 'Jl. Ledjen Suprapto No.95',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Kota',
                'kode_pos'               => '22521',
                'telepon'                => '0631-21300',
                'jam_operasional'        => '17:00-21:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7379,
                'longitude'              => 98.7818,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.737900000000000,98.781800000000004',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '0034U004',
                'nama_faskes'            => 'Praktek Dokter Dr. Ivonna Hasfika',
                'jenis_faskes_id'        => $kln,
                'kategori'               => 'Dokter Praktik Perorangan',
                'alamat'                 => 'Jl. D.I. Panjaitan No.49',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Utara',
                'kode_pos'               => '22521',
                'telepon'                => '0631-21450',
                'jam_operasional'        => '16:00-21:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7448,
                'longitude'              => 98.7809,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.744800000000000,98.780900000000003',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '0034U007',
                'nama_faskes'            => 'Praktek Dokter Dr. Welmansen Situmorang',
                'jenis_faskes_id'        => $kln,
                'kategori'               => 'Dokter Praktik Perorangan',
                'alamat'                 => 'Jl. Suprapto No.45',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Sambas',
                'kode_pos'               => '22521',
                'telepon'                => '0631-21520',
                'jam_operasional'        => '17:00-21:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7343,
                'longitude'              => 98.7846,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.734300000000000,98.784599999999998',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '0034U008',
                'nama_faskes'            => 'Praktek Dokter Dr. Ratna Wati',
                'jenis_faskes_id'        => $kln,
                'kategori'               => 'Dokter Praktik Perorangan',
                'alamat'                 => 'Jl. Sutomo No.11',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Kota',
                'kode_pos'               => '22521',
                'telepon'                => '0631-21580',
                'jam_operasional'        => '16:00-21:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7423,
                'longitude'              => 98.7776,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.742300000000000,98.777600000000007',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '0034U014',
                'nama_faskes'            => 'Praktek Dokter Dr. Rikky N. Harahap',
                'jenis_faskes_id'        => $kln,
                'kategori'               => 'Dokter Praktik Perorangan',
                'alamat'                 => 'Jl. Suprapto No.70',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Kota',
                'kode_pos'               => '22521',
                'telepon'                => '0631-21640',
                'jam_operasional'        => '17:00-21:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7344,
                'longitude'              => 98.7826,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.734400000000000,98.782600000000002',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '0210U002',
                'nama_faskes'            => 'Praktek Dokter Dr. H. Fauzan Amri',
                'jenis_faskes_id'        => $kln,
                'kategori'               => 'Dokter Praktik Perorangan',
                'alamat'                 => 'Jl. S.M. Raja No.289',
                'kelurahan'              => 'Aek Manis',
                'kecamatan'              => 'Sibolga Selatan',
                'kode_pos'               => '22523',
                'telepon'                => '0631-22100',
                'jam_operasional'        => '17:00-21:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7310,
                'longitude'              => 98.7938,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.731000000000000,98.793800000000005',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '340004',
                'nama_faskes'            => 'Poliklinik Polresta Sibolga',
                'jenis_faskes_id'        => $kln,
                'kategori'               => 'Klinik Instansi',
                'alamat'                 => 'Jl. F.L. Tobing No.38',
                'kelurahan'              => 'Pancuran Gerobak',
                'kecamatan'              => 'Sibolga Kota',
                'kode_pos'               => '22521',
                'telepon'                => '0631-21800',
                'jam_operasional'        => '08:00-16:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'POLRI',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7445,
                'longitude'              => 98.7771,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.744500000000000,98.777100000000004',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => 'KLN-SBG-001',
                'nama_faskes'            => 'Klinik Pratama Sibolga Sehat',
                'jenis_faskes_id'        => $kln,
                'kategori'               => 'Klinik Pratama',
                'alamat'                 => 'Jl. Sisingamangaraja No.45',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Selatan',
                'kode_pos'               => '22521',
                'telepon'                => '0631-22456',
                'jam_operasional'        => '08:00-21:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7285,
                'longitude'              => 98.7995,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.728500000000000,98.799499999999995',
                'status'                 => 'Aktif',
            ],

            // ══════════════════════════════════════
            // APOTEK (5 data)
            // ══════════════════════════════════════
            [
                'kode_faskes'            => '0034A001',
                'nama_faskes'            => 'Apotek Segar Sibolga',
                'jenis_faskes_id'        => $apt,
                'kategori'               => 'Apotek',
                'alamat'                 => 'Jl. Suprapto No.116',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Sambas',
                'kode_pos'               => '22521',
                'telepon'                => '0631-21234',
                'jam_operasional'        => '08:00-22:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7338,
                'longitude'              => 98.7847,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.733800000000000,98.784700000000001',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => 'APT-SBG-001',
                'nama_faskes'            => 'Apotek Kimia Farma 0281',
                'jenis_faskes_id'        => $apt,
                'kategori'               => 'Apotek',
                'alamat'                 => 'Jl. Sisingamangaraja No.55',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Selatan',
                'kode_pos'               => '22521',
                'telepon'                => '0631-22100',
                'jam_operasional'        => '08:00-22:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta (BUMN)',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7302,
                'longitude'              => 98.7934,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.730200000000000,98.793400000000005',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => 'APT-SBG-002',
                'nama_faskes'            => 'Apotek K-24 Sibolga',
                'jenis_faskes_id'        => $apt,
                'kategori'               => 'Apotek',
                'alamat'                 => 'Jl. Ahmad Yani No.8',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Utara',
                'kode_pos'               => '22521',
                'telepon'                => '0631-22200',
                'jam_operasional'        => '00:00-24:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7479,
                'longitude'              => 98.7737,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.747900000000000,98.773700000000005',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => 'APT-SBG-003',
                'nama_faskes'            => 'Apotek Sibolga Farma',
                'jenis_faskes_id'        => $apt,
                'kategori'               => 'Apotek',
                'alamat'                 => 'Jl. Dr. F.L. Tobing No.8',
                'kelurahan'              => 'Aek Manis',
                'kecamatan'              => 'Sibolga Kota',
                'kode_pos'               => '22523',
                'telepon'                => '0631-21567',
                'jam_operasional'        => '08:00-21:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => false,
                'latitude'               => 1.7418,
                'longitude'              => 98.7773,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.741800000000000,98.777299999999997',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => 'APT-SBG-004',
                'nama_faskes'            => 'Apotek Sehat Utara',
                'jenis_faskes_id'        => $apt,
                'kategori'               => 'Apotek',
                'alamat'                 => 'Jl. Barangin No.8',
                'kelurahan'              => 'Sibolga Ilir',
                'kecamatan'              => 'Sibolga Kota',
                'kode_pos'               => '22521',
                'telepon'                => '0631-21623',
                'jam_operasional'        => '08:00-21:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => false,
                'latitude'               => 1.7397,
                'longitude'              => 98.7781,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.739700000000000,98.778099999999995',
                'status'                 => 'Aktif',
            ],

            // ══════════════════════════════════════
            // OPTIK (3 data)
            // ══════════════════════════════════════
            [
                'kode_faskes'            => '0034O001',
                'nama_faskes'            => 'Optical ABC Sibolga',
                'jenis_faskes_id'        => $opt,
                'kategori'               => 'Optik',
                'alamat'                 => 'Jl. Ahmad Yani No.55',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Kota',
                'kode_pos'               => '22521',
                'telepon'                => '0631-22300',
                'jam_operasional'        => '08:00-21:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7393,
                'longitude'              => 98.7782,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.739300000000000,98.778199999999998',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '0210O001',
                'nama_faskes'            => 'Lai Optical Sibolga',
                'jenis_faskes_id'        => $opt,
                'kategori'               => 'Optik',
                'alamat'                 => 'Jl. Diponegoro No.40',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Kota',
                'kode_pos'               => '22521',
                'telepon'                => '0631-22350',
                'jam_operasional'        => '08:00-21:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7393,
                'longitude'              => 98.7806,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.739300000000000,98.780600000000007',
                'status'                 => 'Aktif',
            ],
            [
                'kode_faskes'            => '0210O002',
                'nama_faskes'            => 'Asia Optical Sibolga',
                'jenis_faskes_id'        => $opt,
                'kategori'               => 'Optik',
                'alamat'                 => 'Jl. Masjid No.91',
                'kelurahan'              => 'Pasar Baru',
                'kecamatan'              => 'Sibolga Kota',
                'kode_pos'               => '22521',
                'telepon'                => '0631-22380',
                'jam_operasional'        => '08:00-21:00',
                'kapasitas_tempat_tidur' => 0,
                'akreditasi'             => '-',
                'status_kepemilikan'     => 'Swasta',
                'kelas_rs'               => '-',
                'bpjs'                   => true,
                'latitude'               => 1.7386,
                'longitude'              => 98.7789,
                'link_googlemaps'        => 'https://maps.google.com/?q=1.738600000000000,98.778899999999993',
                'status'                 => 'Aktif',
            ],

        ]; // end $data

        foreach ($data as $d) {
            FasilitasKesehatan::create($d);
        }
    }
}
